# Generated by Django 4.0.5 on 2022-06-16 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('surnames', models.CharField(max_length=200, verbose_name='surnames')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$')], verbose_name='phone')),
                ('hobbies', models.TextField(verbose_name='hobbies')),
                ('validated_email', models.BooleanField(default=False, verbose_name='email validated')),
                ('validated_phone', models.BooleanField(default=False, verbose_name='phone validated')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
